; System -
;   OS:  [Linux Mint 22.1 x86 Cinnamon]
;   IDE: [CLion + PlatformIO]
; Author: Zain Ali
;
; This is a new platformio designed for
;   - multiple entry points (Units)
;   - multiple boards / bootloaders
;   - TODO: Zain precompiled binaries
;
; INSTRUCTORS + FACILITATORS
;   - change the [vars] extends = ... to try a different bootloader
;   - if you get recv errors try a different bootloader
;


; -- generic configs --
[vars]
extends = nanoatmega328new
; extends = nanoatmega328 ; switch this line for old bootloader
; extends = esp32_c3_supermini ; a future proofing for later

[platformio]
default_envs = Unit1

[env] ; inherited by everything
framework = arduino
lib_deps =
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    kosme/arduinoFFT @ ^2.0.4

; -- board configs--
[nanoatmega328new]
platform = atmelavr
board = nanoatmega328new
upload_protocol = arduino

[nanoatmega328Old]
platform = atmelavr
board = nanoatmega328
upload_protocol = arduino

[esp32c3_supermini]
platform = espressif32
board = esp32-c3-devkitm-1
monitor_speed = 115200
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DESPPINOUT=1

; -- project compile target configs --
[env:Unit1]
extends = vars
build_src_filter = -<*> +<Unit1/>

[env:Unit2]
extends = vars
build_src_filter = -<*> +<Unit2/>